### ISSUE TITLE
Error in MacOs Mojave

### ISSUE THREAD

**Issue by costeta2** [chris1111/macOSRamDisk#1]
Hi Friend!
I am running your App in my Macbook Pro 12.1 with Mojave, and seems that the app has some bug.

Could you cheack it?

*(Myname) is my user name.

In Terminal, it shows this:

   \033[0;36mmacOS-RamDisk\033[m               
        ***************************************************************
                  
                                 Welcome \033[1m\033[0;35m"(Myname)*"\033[m
 
                                Type \033[1;32m\033[1mA\033[m ➣ to START 
 
                                Type \033[1;31m\033[1mX\033[m ➣ to EXIT
                                
So, when I press A, as you shows in your vid, Appears this:

Value RamDisk size: 
Choose the size Number 
 \033[0;36m⬇︎\033[m                   \033[1;32m⬇︎\033[m   
    
(\033[0;33m256\033[m Mb) ------- = \033[1;32m524288\033[m   
(\033[0;33m512\033[m Mb) ------- = \033[1;32m1048576\033[m 
(\033[0;33m1\033[m Gb) --------- = \033[1;32m2097152\033[m  
(\033[0;33m2\033[m Gb) --------- = \033[1;32m4194304\033[m 
(\033[0;33m3\033[m Gb) --------- = \033[1;32m6294456\033[m
(\033[0;33m4\033[m Gb) --------- = \033[1;32m8391608\033[m  
(\033[0;33m5\033[m Gb) --------- = \033[1;32m10488760\033[m
(\033[0;33m6\033[m Gb) --------- = \033[1;32m12585912\033[m
(\033[0;33m7\033[m Gb) --------- = \033[1;32m14683064\033[m
(\033[0;33m8\033[m Gb) --------- = \033[1;32m16384000\033[m

Thank you!!

**Comment by chris1111** [comment]
Fix for old macOS
[
](https://github.com/chris1111/macOSRamDisk/releases/tag/V1-Terminal-Old)

**Comment by costeta2** [comment]
with that app, appears:

                                Type A ‚û£  to START 
 
                                Type X ‚û£  to EXIT   

What is û£  ‚û£? Is a problem from my macbook?
Thanks!

**Comment by chris1111** [comment]
it's a functional character arrow from 10.10 to Ventura 13 so don't tell me you can't see it because you're on a macBook, I also have a macBook

Sierra 10.12
![Untitled](https://user-images.githubusercontent.com/6248794/217384121-3cd5a39a-3ee9-40e1-abbc-7ee5057b9711.png)
